# Generated by Django 3.1.4 on 2021-03-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
